{% set name = "ocifs" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ocifs-{{ version }}.tar.gz
  sha256: 5e8c28c5d654cbef3e2c6a11f3baa312b2caf922007db05e08c26d8299a952c7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.8
    - pip
  run:
    - python >={{ python_min }}
    - fsspec >=0.8.7
    - oci >=2.43.1
    - requests

test:
  imports:
    - ocifs
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Convenient filesystem interface over Oracle Cloud's Object Storage
  home: https://github.com/oracle/ocifs
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
